# Default (all profiles)
app.greeting=Hello from Quarkus!
app.max-items=10

# Nested config used by @ConfigMapping
app.database.host=localhost
app.database.port=5432
app.database.name=mydb

# Dev profile (%dev) 
%dev.app.greeting=Hello from Quarkus DEV mode!
%dev.app.max-items=100
%dev.app.feature-flag=true
%dev.app.database.name=mydb_dev

# Test profile (%test)
%test.quarkus.http.test-port=0
%test.app.greeting=Hello from Quarkus TEST!
%test.app.max-items=5
%test.app.feature-flag=false

# Prod profile (%prod)
%prod.app.greeting=Hello from Quarkus PROD!
%prod.app.max-items=50
%prod.app.database.host=prod-db.internal
%prod.app.database.name=mydb_prod
